"""Firmware skeleton for the BOM's MCU family. Owner: W20.

    template_files(spec) -> {path: content}           # deterministic, no LLM
    llm_files(spec) -> {path: content}                # LLM route "fast"; raises LLMError
    write_zip(files, dest) -> [paths]

nRF52 → Zephyr (nRF Connect SDK layout: CMakeLists.txt, prj.conf, src/); ESP32 / others → Arduino (PlatformIO).
Every README starts with "Generated code — not compiled or tested".
"""

from __future__ import annotations

import io
import re
import zipfile
from dataclasses import dataclass, field
from pathlib import Path, PurePosixPath

from pydantic import BaseModel, ConfigDict, Field

from api import llm

NOTE = "Generated code — not compiled or tested"
MAX_FILES = 10
MAX_FILE_CHARS = 12000


@dataclass
class FirmwareSpec:
    product: str
    framework: str  # zephyr | arduino
    mcu_family: str
    mcu_part: str
    connectivity: str
    sensors: list[tuple[str, str, str]] = field(default_factory=list)  # (slug, part name, bus)
    actuators: list[tuple[str, str, str]] = field(default_factory=list)


def framework_for(family: str) -> str:
    return "zephyr" if family == "nrf52" else "arduino"


def slug(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")
    return (s[:24].rstrip("_") or "block")


def spec_from(arch, product: str, connectivity: str) -> FirmwareSpec:
    sensors, actuators, seen = [], [], set()
    for line in arch.power_budget:
        kind = line.block
        if kind in ("mcu", "charger", "regulator", "driver"):
            continue
        name = slug(kind if kind not in seen else f"{kind}_{len(seen)}")
        seen.add(kind)
        bus = next((c.bus for c in arch.connections if c.target == line.part and c.bus != "power"), "gpio")
        (sensors if kind in ("imu", "ppg", "env", "gnss", "moisture", "flow", "lidar", "camera") else actuators).append((name, line.part, bus))
    return FirmwareSpec(product=product, framework=framework_for(arch.mcu_family), mcu_family=arch.mcu_family, mcu_part=arch.mcu_part,
                        connectivity=connectivity, sensors=sensors, actuators=actuators)


def _readme(s: FirmwareSpec, generated_by: str) -> str:
    blocks = "\n".join(f"- `{n}` — {p} ({b.upper()})" for n, p, b in s.sensors + s.actuators) or "- (no peripherals in the BOM)"
    build = ("west build -b <your_nrf52_board> . && west flash" if s.framework == "zephyr" else "pio run -t upload   # PlatformIO")
    return f"""# {s.product} — firmware skeleton

> **{NOTE}.** Starting point for bring-up on a dev kit; review every pin, timing and power setting.

- MCU: {s.mcu_part} ({s.mcu_family}) · framework: {s.framework} · connectivity: {s.connectivity}
- Generated by: {generated_by}

## Peripherals (from the BOM)
{blocks}

## Build
```
{build}
```

## Structure
- main loop: sample sensors → update the {("BLE GATT service" if "BLE" in s.connectivity else "MQTT topics" if "MQTT" in s.connectivity else "outputs")} → sleep
- `sensors.*`: one init/read stub per sensor (replace with the vendor driver)
- `{"ble_service" if s.framework == "zephyr" else "connectivity"}.*`: {s.connectivity}

## Next steps
1. Pin map from the schematic (PCB layout is the next step: human or text-to-PCB)
2. Replace every `TODO` stub with the vendor driver, measure sleep current with a power profiler
3. OTA/DFU, watchdog, brown-out handling before any field test
"""


def _zephyr(s: FirmwareSpec) -> dict[str, str]:
    sens = s.sensors
    decl = "\n".join(f"int {n}_init(void);\nint {n}_read(int32_t *out);" for n, _, _ in sens) or "/* no sensors in the BOM */"
    impl = "\n\n".join(
        f"/* {p} on {b.upper()} */\nint {n}_init(void)\n{{\n\t/* TODO: vendor driver init via devicetree node */\n\treturn 0;\n}}\n\n"
        f"int {n}_read(int32_t *out)\n{{\n\t*out = 0; /* TODO: read {p} */\n\treturn 0;\n}}"
        for n, p, b in sens) or "/* no sensors */"
    chars = "\n".join(
        f"\tBT_GATT_CHARACTERISTIC(BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x6e400{i + 2:03x}, 0xb5a3, 0xf393, 0xe0a9, 0xe50e24dcca9e)),\n"
        f"\t\tBT_GATT_CHRC_READ | BT_GATT_CHRC_NOTIFY, BT_GATT_PERM_READ, read_{n}, NULL, &values[{i}]),\n\tBT_GATT_CCC(NULL, BT_GATT_PERM_READ | BT_GATT_PERM_WRITE),"
        for i, (n, _, _) in enumerate(sens))
    reads = "\n".join(f"static ssize_t read_{n}(struct bt_conn *c, const struct bt_gatt_attr *a, void *buf, uint16_t len, uint16_t off)\n"
                      f"{{\n\treturn bt_gatt_attr_read(c, a, buf, len, off, a->user_data, sizeof(int32_t));\n}}" for n, _, _ in sens)
    init_calls = "\n".join(f"\t{n}_init();" for n, _, _ in sens)
    read_calls = "\n".join(f"\t\t{n}_read(&values[{i}]);" for i, (n, _, _) in enumerate(sens))
    n_vals = max(1, len(sens))
    return {
        "CMakeLists.txt": "cmake_minimum_required(VERSION 3.20.0)\nfind_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})\n"
                          f"project({slug(s.product)})\ntarget_sources(app PRIVATE src/main.c src/sensors.c src/ble_service.c)\n",
        "prj.conf": "CONFIG_BT=y\nCONFIG_BT_PERIPHERAL=y\nCONFIG_BT_DEVICE_NAME=\"" + s.product[:20].replace('"', "") + "\"\n"
                    "CONFIG_I2C=y\nCONFIG_SENSOR=y\nCONFIG_PM_DEVICE=y\nCONFIG_LOG=y\n",
        "src/sensors.h": f"#pragma once\n#include <stdint.h>\n\n{decl}\n",
        "src/sensors.c": f"/* {NOTE} */\n#include \"sensors.h\"\n\n{impl}\n",
        "src/ble_service.h": f"#pragma once\n#include <stdint.h>\n\nextern int32_t values[{n_vals}];\nint ble_service_start(void);\nvoid ble_service_notify(void);\n",
        "src/ble_service.c": f"/* {NOTE} — custom GATT service, one characteristic per sensor */\n#include <zephyr/bluetooth/bluetooth.h>\n"
                             f"#include <zephyr/bluetooth/gatt.h>\n#include \"ble_service.h\"\n\nint32_t values[{n_vals}];\n\n{reads}\n\n"
                             "BT_GATT_SERVICE_DEFINE(product_svc,\n\tBT_GATT_PRIMARY_SERVICE(BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x6e400001, 0xb5a3, 0xf393, 0xe0a9, 0xe50e24dcca9e))),\n"
                             f"{chars}\n);\n\nint ble_service_start(void)\n{{\n\tint err = bt_enable(NULL);\n\tif (err) {{\n\t\treturn err;\n\t}}\n"
                             "\tstatic const struct bt_data ad[] = {BT_DATA_BYTES(BT_DATA_FLAGS, BT_LE_AD_GENERAL | BT_LE_AD_NO_BREDR)};\n"
                             "\treturn bt_le_adv_start(BT_LE_ADV_CONN, ad, ARRAY_SIZE(ad), NULL, 0);\n}\n\nvoid ble_service_notify(void)\n{\n\t/* TODO: bt_gatt_notify per characteristic when a client subscribed */\n}\n",
        "src/main.c": f"/* {NOTE} */\n#include <zephyr/kernel.h>\n#include \"sensors.h\"\n#include \"ble_service.h\"\n\n"
                      f"#define SAMPLE_PERIOD_MS 1000\n\nint main(void)\n{{\n{init_calls}\n\tble_service_start();\n\twhile (1) {{\n{read_calls}\n"
                      "\t\tble_service_notify();\n\t\tk_msleep(SAMPLE_PERIOD_MS); /* idle thread → System ON sleep */\n\t}\n\treturn 0;\n}\n",
    }


def _arduino(s: FirmwareSpec) -> dict[str, str]:
    sens, acts = s.sensors, s.actuators
    mqtt = "MQTT" in s.connectivity
    ble = not mqtt and "BLE" in s.connectivity
    pins = "\n".join(f"#define PIN_{n.upper()} {12 + i}  // TODO: from the schematic ({p})" for i, (n, p, _) in enumerate(sens + acts))
    decl = "\n".join(f"void {n}_init();\nfloat {n}_read();" for n, _, _ in sens)
    impl = "\n\n".join(f"// {p} ({b.upper()})\nvoid {n}_init() {{ /* TODO: vendor library begin() */ }}\nfloat {n}_read() {{ return 0.0f; /* TODO */ }}"
                       for n, p, b in sens)
    publish = "\n".join(f'  publishValue("{n}", {n}_read());' for n, _, _ in sens)
    if mqtt:
        conn_h = "#pragma once\n#include <Arduino.h>\nvoid connectivity_begin();\nvoid connectivity_loop();\nvoid publishValue(const char *name, float v);\n"
        conn_c = (f"// {NOTE}\n#include <WiFi.h>\n#include <PubSubClient.h>\n#include \"connectivity.h\"\n\n"
                  "static const char *WIFI_SSID = \"TODO\";\nstatic const char *WIFI_PASS = \"TODO\";\nstatic const char *MQTT_HOST = \"TODO\";\n"
                  "static WiFiClient net;\nstatic PubSubClient mqtt(net);\n\nvoid connectivity_begin() {\n  WiFi.begin(WIFI_SSID, WIFI_PASS);\n"
                  "  mqtt.setServer(MQTT_HOST, 1883);\n}\n\nvoid connectivity_loop() {\n  if (WiFi.status() == WL_CONNECTED && !mqtt.connected()) mqtt.connect(\"" + slug(s.product) + "\");\n  mqtt.loop();\n}\n\n"
                  "void publishValue(const char *name, float v) {\n  char topic[64];\n  snprintf(topic, sizeof topic, \"" + slug(s.product) + "/%s\", name);\n"
                  "  char payload[16];\n  dtostrf(v, 0, 3, payload);\n  mqtt.publish(topic, payload);\n}\n")
        lib = "lib_deps = knolleary/PubSubClient@^2.8\n"
    else:
        conn_h = "#pragma once\n#include <Arduino.h>\nvoid connectivity_begin();\nvoid connectivity_loop();\nvoid publishValue(const char *name, float v);\n"
        conn_c = (f"// {NOTE}\n#include \"connectivity.h\"\n" + ("#include <NimBLEDevice.h>\n\nstatic NimBLECharacteristic *chr;\n\nvoid connectivity_begin() {\n"
                  f"  NimBLEDevice::init(\"{s.product[:20]}\");\n  auto *svc = NimBLEDevice::createServer()->createService(\"6e400001-b5a3-f393-e0a9-e50e24dcca9e\");\n"
                  "  chr = svc->createCharacteristic(\"6e400002-b5a3-f393-e0a9-e50e24dcca9e\", NIMBLE_PROPERTY::READ | NIMBLE_PROPERTY::NOTIFY);\n"
                  "  svc->start();\n  NimBLEDevice::getAdvertising()->start();\n}\n\nvoid connectivity_loop() {}\n\n"
                  "void publishValue(const char *name, float v) {\n  chr->setValue(v);\n  chr->notify();\n}\n" if ble else
                  "\nvoid connectivity_begin() {}\nvoid connectivity_loop() {}\nvoid publishValue(const char *name, float v) {\n  Serial.printf(\"%s=%.3f\\n\", name, v);\n}\n"))
        lib = "lib_deps = h2zero/NimBLE-Arduino@^1.4\n" if ble else ""
    board = "esp32-c3-devkitm-1" if s.mcu_family == "esp32" else "TODO_board"
    platform = "espressif32" if s.mcu_family == "esp32" else "TODO_platform"
    acts_code = "\n".join(f"  pinMode(PIN_{n.upper()}, OUTPUT);  // {p}" for n, p, _ in acts)
    return {
        "platformio.ini": f"[env:proto]\nplatform = {platform}\nboard = {board}\nframework = arduino\nmonitor_speed = 115200\n{lib}",
        "src/pins.h": f"#pragma once\n// {NOTE}\n{pins or '// no peripherals'}\n",
        "src/sensors.h": f"#pragma once\n{decl or '// no sensors'}\n",
        "src/sensors.cpp": f"// {NOTE}\n#include \"sensors.h\"\n\n{impl or '// no sensors'}\n",
        "src/connectivity.h": conn_h,
        "src/connectivity.cpp": conn_c,
        "src/main.cpp": f"// {NOTE}\n#include <Arduino.h>\n#include \"pins.h\"\n#include \"sensors.h\"\n#include \"connectivity.h\"\n\n"
                        "static const uint32_t SAMPLE_PERIOD_MS = 1000;\n\nvoid setup() {\n  Serial.begin(115200);\n"
                        + "\n".join(f"  {n}_init();" for n, _, _ in sens) + f"\n{acts_code}\n  connectivity_begin();\n}}\n\n"
                        f"void loop() {{\n  connectivity_loop();\n{publish}\n  delay(SAMPLE_PERIOD_MS);  // TODO: light/deep sleep for battery products\n}}\n",
    }


def template_files(s: FirmwareSpec) -> dict[str, str]:
    files = _zephyr(s) if s.framework == "zephyr" else _arduino(s)
    return {"README.md": _readme(s, "template"), **files}


class _File(BaseModel):
    model_config = ConfigDict(extra="ignore")
    path: str
    content: str


class FirmwareDraft(BaseModel):
    model_config = ConfigDict(extra="ignore")
    files: list[_File] = Field(min_length=2, max_length=MAX_FILES)


_SAFE = re.compile(r"^[A-Za-z0-9_][A-Za-z0-9_./-]{0,80}$")


def llm_files(s: FirmwareSpec) -> tuple[dict[str, str], str]:
    """(files, generated_by). Raises LLMError when unavailable/invalid (caller keeps the template)."""
    layout = ("Zephyr RTOS (nRF Connect SDK) project: CMakeLists.txt, prj.conf, src/main.c, src/sensors.c/.h, src/ble_service.c/.h "
              "with a custom BLE GATT service (one notify characteristic per sensor)" if s.framework == "zephyr" else
              f"PlatformIO Arduino project: platformio.ini, src/main.cpp, src/pins.h, src/sensors.cpp/.h, src/connectivity.cpp/.h implementing {s.connectivity}")
    periph = "\n".join(f"- {n}: {p} on {b.upper()}" for n, p, b in s.sensors + s.actuators) or "- none"
    prompt = (f"Write a SMALL firmware skeleton for the product '{s.product}'. MCU: {s.mcu_part} ({s.mcu_family}). {layout}.\n"
              f"Peripherals from the BOM:\n{periph}\n"
              "Rules: main loop samples sensors, publishes values, then sleeps; each sensor driver is an init/read stub with TODO "
              "comments (no invented register maps); keep every file under 120 lines; no README (it is added separately). "
              f"Return JSON {{\"files\": [{{\"path\": \"...\", \"content\": \"...\"}}]}} with at most {MAX_FILES - 1} files.")
    draft = llm.complete_json("fast", prompt, FirmwareDraft, system="You are a senior embedded firmware engineer.", max_tokens=6000, timeout_s=60)
    files: dict[str, str] = {}
    for f in draft.files:
        raw = f.path.strip()
        path = raw.removeprefix("./")
        if ".." in PurePosixPath(raw).parts or not _SAFE.match(path) or path.lower() == "readme.md":
            continue
        files[path] = f.content[:MAX_FILE_CHARS]
    if len(files) < 2:
        raise llm.LLMValidationError("fast", "firmware draft has fewer than 2 usable files")
    tag = f"llm:{llm.model_for('fast')}"
    return {"README.md": _readme(s, tag), **files}, tag


def write_zip(files: dict[str, str], dest: Path, root: str = "firmware") -> list[str]:
    dest.parent.mkdir(parents=True, exist_ok=True)
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for path, content in sorted(files.items()):
            z.writestr(f"{root}/{path}", content)
    tmp = dest.with_suffix(".zip.tmp")
    tmp.write_bytes(buf.getvalue())
    tmp.replace(dest)  # atomic: a GET never serves a half-written zip
    return sorted(files)
